"""Iter38r-fix9p — Public docs (PDF) download endpoints.

Three flagship documents generated by `/app/docs/generate_pdfs.py`:
  - A_Guide_Utilisateur_SAWALI_Loois.pdf
  - B_Brochure_Presentation_SAWALI_Loois.pdf
  - C_Brochure_Grandes_Fonctionnalites.pdf
"""
from __future__ import annotations
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

DOCS_DIR = Path("/app/docs")
DOCS = {
    "guide-utilisateur": "A_Guide_Utilisateur_SAWALI_Loois.pdf",
    "brochure-presentation": "B_Brochure_Presentation_SAWALI_Loois.pdf",
    "brochure-fonctionnalites": "C_Brochure_Grandes_Fonctionnalites.pdf",
}


def setup_docs_routes(*, api: APIRouter):
    @api.get("/public/docs", tags=["Public — Docs"])
    async def list_docs():
        items = []
        for slug, fname in DOCS.items():
            p = DOCS_DIR / fname
            if p.exists():
                items.append({
                    "slug": slug,
                    "filename": fname,
                    "size_kb": p.stat().st_size // 1024,
                    "url": f"/api/public/docs/{slug}",
                })
        return {"items": items}

    @api.get("/public/docs/{slug}", tags=["Public — Docs"])
    async def download_doc(slug: str):
        fname = DOCS.get(slug)
        if not fname:
            raise HTTPException(404, "Document inconnu")
        p = DOCS_DIR / fname
        if not p.exists():
            raise HTTPException(404, "Fichier non trouvé")
        return FileResponse(
            str(p),
            media_type="application/pdf",
            filename=fname,
            headers={"Content-Disposition": f'inline; filename="{fname}"'},
        )

    return api
